spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
#    指定flyway的基线版本
  flyway:
    baseline-on-migrate: true
    baseline-version: 20230504001
logging:
  level:
    root: info
  file:
    name: logs/platform.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/platform-%d{yyyy-MM-dd}.%i.log